baseURL = "https://jacobboes.com"
languageCode = "en-us"
title = "Due Dissidence"
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 30
enableRobotsTXT = "true"
[params]
  description = "Political commentary, interviews, & satire."
  author = "Due Dissidence"
