baseURL = "https://jacobboes.com"
languageCode = "en-us"
title = "Due Dissidence"
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 30
enableRobotsTXT = "true"
ignoreErrors = ["error-remote-getjson"]
[params]
  description = "Post Duopoly Left"
  author = "Due Dissidence"
